module.exports = {
  "automerge": true,
  "commitMessageExtra": "to {{newVersion}}",
  "commitMessageSuffix": "",
  "commitMessageTopic": "{{depName}}",
  "dependencyDashboard": false,
  "dryRun": null,
  "extends": ["config:recommended", ":rebaseStalePrs"],
  "gitAuthor": "szymonrichert.pl bot <bot@szymonrichert.pl>",
  "onboarding": false,
  "pinDigests": true,
  "platform": "github",
  "prConcurrentLimit": 100,
  "rebaseWhen": "conflicted",
  "repositories": ["szymonrychu/selfhosted-kubernetes-containers"],
  "semanticCommits": "enabled",
  "suppressNotifications": ["prIgnoreNotification"],
  "username": "szymonrichert.pl bot",
};