module.exports = {
  "automerge": true,
  "commitMessageExtra": "to {{newVersion}}",
  "commitMessageSuffix": "",
  "commitMessageTopic": "{{depName}}",
  "allowedPostUpgradeCommands": [".*"],
  "dependencyDashboard": false,
  "dryRun": null,
  "extends": ["config:recommended", ":rebaseStalePrs"],
  "gitAuthor": "szymonrichert.pl bot <bot@szymonrichert.pl>",
  "pinDigests": true,
  "prConcurrentLimit": 100,
  "rebaseWhen": "conflicted",
  "semanticCommits": "enabled",
  "suppressNotifications": ["prIgnoreNotification"],
  "username": "szymonrichert.pl bot",
  "platform": "gitlab",
  "endpoint": process.env.CI_API_V4_URL,
  "token": process.env.BOT_TOKEN,
  "onboarding": false,
  "onboardingConfig": {
    extends: ['config:recommended'],
  },
  "repositories": [process.env.CI_PROJECT_PATH]
};