name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@936628dfbff213ab2eb95033c5e123cfcaf09ebb # v41.0.5
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true