name: "Containers Test"

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-22.04
    outputs:
      changed_containers: ${{ steps.changed_containers.outputs.changed_containers }}
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Get all test, doc and src files that have changed
      id: changed_files
      uses: tj-actions/changed-files@1754cd4b9e661d1f0eced3b33545a8d8b3bc46d8 # v44
      with:
        json: true
        escape_json: false
        dir_names: true
        dir_names_max_depth: 2
    - name: Filter release names
      id: changed_containers
      run: |
        ./.github/filter_paths.py '${{ steps.changed_files.outputs.all_changed_files }}' >> "$GITHUB_OUTPUT"

  build:
    name: Build
    runs-on: ubuntu-22.04
    needs:
    - changes
    strategy:
      matrix:
        container_path: ${{ fromJson(needs.changes.outputs.changed_containers) }}
      fail-fast: false
    if: needs.changes.outputs.changed_containers != '[]'
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Login to GHCR
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
      
    - name: Prepare
      id: prep
      run: |
        echo "container=$(basename ${{ matrix.container_path }})" >> "$GITHUB_OUTPUT"
        echo "version=$(cat ${{ matrix.container_path }}/VERSION)" >> "$GITHUB_OUTPUT"
        echo "short_sha=$(echo "${GITHUB_SHA}" | cut -c1-8)" >> "$GITHUB_OUTPUT"

    # Push if not a PR, otherwise just test the build process for all requested platforms
    - name: Build and Push
      id: push
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
      with:
        context: ${{ matrix.container_path }}/
        platforms: linux/amd64
        file: ${{ matrix.container_path }}/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ steps.prep.outputs.container }}:dev-${{ steps.prep.outputs.short_sha }}
  
  container-build-complete:
    needs: [build]
    name: Container Build Completed
    runs-on: ubuntu-latest
    steps:
      - name: complete message
        run: echo "Container Build and Tests Completed Successfully"
